services:
  mysql:
    image: mysql:8.0
    container_name: fastapi-websocket-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: qwerasd
      MYSQL_DATABASE: websocket-study

    ports:
      - "3309:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: fastapi-websocket-redis
    restart: always

    ports:
      - "6380:6379"

    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: